//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TramWidget.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TramWidget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C.
        /// </summary>
        public static string DefaultLine1 {
            get {
                return ResourceManager.GetString("DefaultLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E.
        /// </summary>
        public static string DefaultLine2 {
            get {
                return ResourceManager.GetString("DefaultLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://data.metromobilite.fr/api/routers/default/index/stops/{0}/stoptimes.
        /// </summary>
        public static string DefaultLinkAddress {
            get {
                return ResourceManager.GetString("DefaultLinkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEM:2236.
        /// </summary>
        public static string DefaultTram1 {
            get {
                return ResourceManager.GetString("DefaultTram1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEM:2235.
        /// </summary>
        public static string DefaultTram2 {
            get {
                return ResourceManager.GetString("DefaultTram2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEM:3205.
        /// </summary>
        public static string DefaultTram3 {
            get {
                return ResourceManager.GetString("DefaultTram3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEM:3206.
        /// </summary>
        public static string DefaultTram4 {
            get {
                return ResourceManager.GetString("DefaultTram4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 59000.
        /// </summary>
        public static string DefaultTramPullFrequency {
            get {
                return ResourceManager.GetString("DefaultTramPullFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -.
        /// </summary>
        public static string DefaultTramText {
            get {
                return ResourceManager.GetString("DefaultTramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligne 1.
        /// </summary>
        public static string Line1 {
            get {
                return ResourceManager.GetString("Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligne 2.
        /// </summary>
        public static string Line2 {
            get {
                return ResourceManager.GetString("Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse métromobilité.
        /// </summary>
        public static string LinkAddress {
            get {
                return ResourceManager.GetString("LinkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TramWidget.conf.
        /// </summary>
        public static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tram 1.
        /// </summary>
        public static string Tram1 {
            get {
                return ResourceManager.GetString("Tram1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tram 2.
        /// </summary>
        public static string Tram2 {
            get {
                return ResourceManager.GetString("Tram2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tram 3.
        /// </summary>
        public static string Tram3 {
            get {
                return ResourceManager.GetString("Tram3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tram 4.
        /// </summary>
        public static string Tram4 {
            get {
                return ResourceManager.GetString("Tram4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Période de rafraîchissement (ms).
        /// </summary>
        public static string TramPullFrequency {
            get {
                return ResourceManager.GetString("TramPullFrequency", resourceCulture);
            }
        }
    }
}
